"""
Mock LLM - Rule-based engine providing preset responses for CrewAI Agents
Appears like a real LLM but uses rule matching internally
"""
import asyncio
import random


class MockLLM:
    """Mock LLM for CrewAI - Rule engine disguised as LLM"""

    def __init__(self, agent_type: str):
        self.agent_type = agent_type
        self.model_name = "mock-llm-v1"

    def __call__(self, prompt: str, **kwargs) -> str:
        """CrewAI call entry point - synchronous method"""
        return self._get_response(prompt)

    async def acall(self, prompt: str, **kwargs) -> str:
        """Async call entry point"""
        # Simulate AI thinking delay
        await asyncio.sleep(random.uniform(0.2, 0.5))
        return self._get_response(prompt)

    def _get_response(self, prompt: str) -> str:
        """Return preset response based on agent_type"""
        responses = MOCK_RESPONSES.get(self.agent_type, {})

        # Try to match more specific response based on prompt keywords
        for keyword, response in responses.items():
            if keyword != "default" and keyword in prompt.lower():
                return response

        return responses.get("default", "Task completed.")


# Preset response library - categorized by agent_type
MOCK_RESPONSES = {
    # Requirement analysis group experts
    "planner": {
        "default": """**Task Planning Complete**

I have analyzed the user requirements. Task assignments:
1. BA Expert: Business process analysis, identify business elements
2. Tech Expert: Technical solution design, determine interface specifications
3. Summarizer: Consolidate analysis from all parties, generate structured output

Experts please proceed in order.""",
        "dividend": """**Dividend Processing Task Planning**

Task breakdown:
1. BA Expert: Analyze dividend business process (record date, ex-date, payment flow)
2. Tech Expert: Design dividend calculation and distribution interfaces
3. Summarizer: Consolidate and generate SIPOC requirement document

Starting execution..."""
    },

    "ba": {
        "default": """**Business Analysis Complete**

SIPOC Business Elements Identified:
- **Supplier**: Fund companies, custody bank data systems
- **Input**: Business request parameters, authorization info
- **Process**: Data retrieval -> Business processing -> Result validation -> Output generation
- **Output**: Processing results, status reports
- **Customer**: Investors, fund managers, regulators""",

        "dividend": """**Dividend Business Analysis Complete**

SIPOC Business Elements:
- **Supplier**: Fund companies, custody bank, investor account systems
- **Input**: Dividend fund list, distribution method (cash/reinvest), record date, ex-date
- **Process**:
  1. Retrieve pending dividend fund list
  2. Validate dividend announcement info
  3. Calculate distribution amount per investor
  4. Execute dividend distribution/reinvestment
  5. Update account balances
  6. Generate dividend confirmation report
- **Output**: Dividend processing results, account change records, dividend report
- **Customer**: Investors, fund managers, audit institutions"""
    },

    "tech": {
        "default": """**Technical Analysis Complete**

Technical Implementation:
- **Data Source**: Services from service registry
- **Interface Design**: RESTful API style
- **Parameter Spec**: JSON format input/output
- **Error Handling**: Standard error codes + descriptions
- **Performance Requirement**: Response time < 2s""",

        "dividend": """**Dividend Technical Solution**

Implementation:
- **Service Interface**: `process_dividend(fund_codes: list, method: str)`
- **Data Source**: FUND_DATA, DIVIDEND_DATA
- **Return Format**:
  ```json
  {
    "processed_count": int,
    "total_amount": float,
    "details": [...]
  }
  ```
- **Transaction Handling**: Supports rollback mechanism"""
    },

    "summarizer": {
        "default": """**Requirements Summary Complete**

Expert analysis results consolidated, structured requirement document generated.
- Business process confirmed
- Technical solution reviewed
- SIPOC elements complete

Ready for next phase: SIPOC document generation.""",

        "dividend": """**Dividend Requirements Summary**

BA and Tech analysis consolidated, requirements clarified:
- Process Type: Fund dividend processing
- Core Function: Batch dividend distribution
- Supported Methods: Cash dividend, dividend reinvestment
- Output Format: Processing statistics + detail records

Requirement analysis complete, ready to generate SIPOC document."""
    },

    # Build execution group experts
    "code_generator": {
        "default": """**Service Code Generation Complete**

Generated service implementation based on SIPOC document:
- Service Name: AutoGeneratedService
- Entry Function: execute(params)
- Parameter Validation: Done
- Error Handling: Done
- Logging: Done

Code ready for validation.""",

        "dividend": """**Dividend Service Code Generated**

Service Implementation:
```python
async def process_fund_dividend(fund_codes, method="cash"):
    # 1. Validate fund codes
    # 2. Retrieve dividend info
    # 3. Calculate dividend amounts
    # 4. Execute distribution
    # 5. Return results
    return {"processed_count": N, "total_amount": M}
```

Code generation complete."""
    },

    "validator": {
        "default": """**Code Validation Passed**

Validation Items:
- [PASS] Syntax check: Passed
- [PASS] Parameter validation: Complete
- [PASS] Error handling: Covered
- [PASS] Return format: Compliant
- [PASS] Security check: No risks

Code is safe to execute."""
    },

    "executor": {
        "default": """**Service Execution Complete**

Execution Status: Success
Execution Time: 0.5s
Results returned."""
    },

    # Flow 1 execution group experts
    "formatter": {
        "default": """**Result Formatting Complete**

Data converted to user-friendly display format.""",

        "nav": """**NAV Data Formatted**

Generated Markdown table format NAV information.""",

        "dividend": """**Dividend Result Formatted**

Generated dividend processing statistics table and detail list."""
    },

    "rag_matcher": {
        "default": """**Service Matching Complete**

Found matching service in service registry.
- Match Score: 95%
- Service Status: Available"""
    }
}


class MockLLMWrapper:
    """Wrapper class to ensure CrewAI LLM interface compatibility"""

    def __init__(self, agent_type: str):
        self.llm = MockLLM(agent_type)
        self.model = "mock-llm-v1"

    def __call__(self, messages, **kwargs):
        """Handle CrewAI message format calls"""
        if isinstance(messages, list) and len(messages) > 0:
            # Extract content from last message
            last_message = messages[-1]
            if isinstance(last_message, dict):
                prompt = last_message.get("content", "")
            else:
                prompt = str(last_message)
        else:
            prompt = str(messages)

        response = self.llm(prompt)
        return response
